# Generated by Django 5.1.4 on 2026-06-14 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_token', models.CharField(max_length=100, unique=True)),
                ('flow_order_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Rechazado'), (4, 'Anulado')], default=1)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
